Separate pyse
transientskp/tkp pull request #619
Opened 2024-07-16 09:38 UTC by tmillenaar

2024-07-16 09:44 UTC, HannoSpreeuw commented
I guess this also needs @suvayu 's review, so I'll add him.

2024-07-16 12:58 UTC, suvayu requested changes

2024-07-16 12:58 UTC, suvayu commented on tkp/accessors/__init__.py
This subpackage is now [provided by PySE](https://github.com/transientskp/pyse/tree/master/sourcefinder/accessors), I think these should also go.  So the corresponding imports would have to be modified to `from sourcefinder.accessors ...`

2024-07-16 18:37 UTC, suvayu commented on tkp/accessors/__init__.py
Bug fix version released: https://github.com/transientskp/pyse/releases/tag/v0.3.1

2024-07-17 07:37 UTC, tmillenaar commented on tkp/accessors/__init__.py
Great! Thanks for the quick response.
Since pyse >0.3.x requires python >=3.10 and I am running the cicd in an ancient casacore container I cannot install it yet, but I will try to push some buttons here to get python-casacore updated and then all should work again in harmony :)

2024-07-17 07:57 UTC, AntoniaR commented on tkp/accessors/__init__.py
Not sure if this helps, but with Conda with python 3.11, I got `pip install python-casacore` to work.

2024-07-17 08:58 UTC, AntoniaR commented on tkp/accessors/__init__.py
We are using an old supercomputer and this was the easiest way to get everything working correctly, enable users to install their own python packages and use different TraP versions.

2024-07-17 12:00 UTC, tmillenaar commented on tkp/accessors/__init__.py
Yeah, in the TraP test suite there are two tests that fail if you install python-casacore without using the cascore container. These are:
tests/test_quality/test_brightsource.py::TestEphemeris::test_invalid_ephemeris
tests/test_quality/test_brightsource.py::TestBrightsource::test_brightsource

If I don't run in the container I get the error:
```
RuntimeError: 2024-07-17 11:52:32	SEVERE	MeasTable::dUTC(Double) (file /code/measures/Measures/MeasTable.cc, line 4283)	Cannot read leap second table TAI_UTC
```

They need some look up tables that don't come packaged with python-casacore at the moment. I imagine the PySE tests don't need these tables and Antonia surely put these tables manually on her system a long time ago in a way that casacore can find them. There are workarounds for this, adding a download command that puts these tables where casacore expects them for example, but I prefer to wait on the python-casacore release that includes these tables in the binary.

2024-07-17 13:04 UTC, suvayu commented on tkp/accessors/__init__.py
Okay, I understand now. It's not worth the effort to make this work now since the new `python-casacore` release will solve this issue.  Thanks for explaining the issue again.

2024-07-17 13:15 UTC, suvayu commented on tkp/testutil/mock.py
The `testutil` subpackage is also in PySE.  But maybe this duplication is fine, since they are used in both, and from now on they can evolve independently (i.e. no need to sync in the future).

2024-07-17 13:15 UTC, suvayu approved these changes

2024-07-17 14:58 UTC, HannoSpreeuw commented on tkp/testutil/mock.py
Fixes #616 I reckon.

2024-07-17 14:59 UTC, HannoSpreeuw commented
Fixes https://github.com/transientskp/tkp/issues/616 I reckon.

2024-07-17 15:00 UTC, HannoSpreeuw approved these changes

2024-07-17 15:02 UTC, HannoSpreeuw commented
But we still have the `ERROR: No matching distribution found for radio-pyse>=0.3.1 (from tkp==4.0)` build problem.

2024-07-17 15:33 UTC, suvayu commented
I think that's because of the container issue.  It's using an older Python, and since 0.3.0, PySE requires 3.10.  This will be resolved when `python-casacore` makes a new release, as then there would be no need for the container.

2024-09-03 07:18 UTC, merged